version: '3.1'

services:
    mysql:
        image: mysql
        environment: 
            MYSQL_USER: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: supersecretdbpass 
        # deploy to manager so it is easy to find container for exec'ing in
        deploy:
            placement:
                constraints:
                    - node.role==manager
